### ISSUE TITLE
[Study] GitHub Action 和 Fly.io 整合

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#10]
身為 開發者
我希望 main branch changed 的時候，會自動部署到對應環境
如此 我才不用手動部署

# 背景
目前都是自己在 local 透過 fly.io CLI tool 的方式去部署

# Definition of Done 
1.  順利在 code merge main branch 的時候將服務部署上去

**Comment by s9891326** [comment]
- 這我之前有寫過yaml檔，感覺可以直接搬過來用
![image](https://user-images.githubusercontent.com/44540755/205501981-ca7554b9-79fd-43ba-aca3-7577267d85d9.png)

**Comment by chen-tf** [comment]
那剩下的，會是需要切分環境 deploy，我會來準備一個 dev 版本的 fly.io 環境，之後 main branch 會部署在這個之上，release branch 會對應到正式環境，這邊再看看可以怎麼切分

**Comment by s9891326** [comment]
恩恩，google後發現可以再設定另外一個.yaml來監聽`release create`在進行觸發的事件
![image](https://user-images.githubusercontent.com/44540755/205541557-b6bb79a5-440e-4547-90e0-9fd1e7d18994.png)
![image](https://user-images.githubusercontent.com/44540755/205541584-103fc44b-ec41-4ea7-b205-fe322c36cd70.png)

**Comment by s9891326** [comment]
> 恩恩，google後發現可以再設定另外一個.yaml來監聽`release create`在進行觸發的事件 
- 這是當時理解錯誤XD，以為是要發release的時候去觸發action，所以才在`on`那邊設定`release: create`
