### ISSUE TITLE
Arrival notice not work

### ISSUE THREAD

**Issue by jacky995566** [chen-tf/price-tracker-bot#108]
in pt_service.py line 83
`follow_good_chat_ids = user_repository.find_all_user_by_good_id(good_id)`
`find_all_user_by_good_id` >> will return user list (List[User]) instead of chat_ids list (List[string])

in pt_service.py line 86
`pt_bot.send( )` >> can only accept msg (string) and chat_id (string or int)

in pt_service.py line 88
`str(follow_good_chat_id)` >> this will convert User in database to string.
suggest change to `str(follow_good_chat_id.chat_id)`

**Comment by chen-tf** [comment]
Thank you for reporting the issue. I will adjust it as soon as possible.

**Comment by chen-tf** [comment]
The problem has been resolved. We can now successfully see the launch notification.
<img width="522" alt="image" src="https://github.com/chen-tf/price-tracker-bot/assets/88727350/f6ab947f-12bc-4989-9c40-9a16e985418e">
