### ISSUE TITLE
[Study] Python telegram bot + Flask

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#13]
身為 要出錢去平台開機器的苦主
我希望 `notifier_web.py` 和 `pt_bot.py` 都能使用 Flask 來接收 http request
如此 我就不用開兩台機器分別執行他們

# Definition of Done 
application 可以同時接受 LINE notify & Telegram Bot Webhook

**Comment by chil2020** [comment]
這不能起不同的port 放在同一台機器嗎? 哈哈 ,  line notify之前有玩過,  這我可以去研究看看

**Comment by hokou** [comment]
原來有 2 組，我一開始還從檔案裡找 app.py 找不到

還是說可以用自訂的 API (網址/api)增加？
這樣就可以共用 port

**Comment by chil2020** [comment]
fly.io好像可以用Nginx , 要再去看看了

**Comment by chen-tf** [comment]
https://github.com/sjfbo/video-to-gif-telegram-bot/blob/master/app.py
今天先跟 Payon 討論後，會先把 TelegramBot 的寫法改成像是上面這個 example 的樣子，和 Flask 整在一起。
