### ISSUE TITLE
[Study] Health check

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#14]
身為 開發者
我希望 服務狀態異常的時候收到通知
如此 我才可以緊急進行處理，避免影響到太多使用者

# Definition of Done 
1. define key metric (要怎麼樣我們的服務才算是活著？）
2. 如何做到 health check

**Comment by chil2020** [comment]
之前會寫一個排程(每分鐘1次), 定時發送http request, 當沒有收到200  就發line Notify + 異常訊息 , 至於health check的部分我再去study

**Comment by IamSaker** [comment]
> 之前會寫一個排程(每分鐘1次), 定時發送http request, 當沒有收到200 就發line Notify + 異常訊息 , 至於health check的部分我再去study

理解是開一支 /health，如後使用 [Cron](https://fly.io/docs/laravel/the-basics/cron-and-queues/) 去 request，不是 200 或 500 做對應的處理。
但我看到 fly.io 的 [troubleshooting](https://fly.io/docs/getting-started/troubleshooting/)，或許也是一種 health check 的可行方法。

**Comment by chen-tf** [comment]
先簡單做，可以單純就開一個 endpoint /health 去戳看看，拿到 http 200 就視為服務健康的活著，失敗的話可以打 Discord Webhook 做通知。
未來可以針對一些重要功能的 endpoint 做監控。

**Comment by chen-tf** [comment]
目前開一個 endpoint 單純監測是否 return 200 來作為依據。
