### ISSUE TITLE
[Study] Apply python formatter

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#17]
身為 開發者
我希望 有 formatter 可以幫助排版，讓大家的格式都可以統一
如此 協作起來才可以更順利

# Definition of Done 
1.  要使用哪一個 formatter
2. 如何下 command 檢查目前專案中是否有不符合規定的格式存在

**Comment by w305jack** [comment]
先列一下可以用的 Python Formatter。

1. Formatter 御三家。
- [black](https://github.com/psf/black) (⭐️ 30.4k) - 勝
- [yapf](https://github.com/google/yapf) (⭐️ 12.9k)
- [autopep8](https://github.com/hhatto/autopep8) (⭐️ 4.2k)

2. black 指令基本上就一行。
``` bash
# usage
$ black {source_file_or_directory}

# e.g.
$ black foo.py

reformatted foo.py

All done! ✨ 🍰 ✨
1 files reformatted.
``` 

3. Linter。
- [flake8](https://github.com/PyCQA/flake8)
- [pylint](https://github.com/PyCQA/pylint) (個人開發上比較常用，Pycharm 有出 Plugin 的關係)

以上是先列出選項，順便詢問一下大家在開發上，比較偏好哪種搭配。

(上述的都能寫成 script 放在 CI/CD 裡)
