### ISSUE TITLE
TG顯示已經可以購買，但是網頁的價格沒有變動

### ISSUE THREAD

**Issue by MrLuke1110** [chen-tf/price-tracker-bot#4]
telegram看到已經可以購買，
但是連到MOMO看不出價格的變化，
本來想說是不是因為家電下殺日，
但是商品也不在條件當中…
不確定是什麼原因…
![2022-02-18_16-59-37](https://user-images.githubusercontent.com/66194793/154651497-7d211ae4-5ed7-4eda-af24-52abd871ee0a.png)
![2022-02-18_16-59-09](https://user-images.githubusercontent.com/66194793/154651548-fd75037e-a7df-484b-8c35-895ec98cfed6.png)

**Comment by chen-tf** [comment]
@MrLuke1110 這部分會有通知，是因為貨品曾經缺貨，目前補貨後造成的狀態變更。
與產品降價的無關，之後會考慮把降價以及貨品可購買狀態的通知訂閱做拆分。

**Comment by MrLuke1110** [comment]
多謝回覆，以為是一直都有貨，所以才想是不是有什麼特價優惠，是我沒注意到的
