### ISSUE TITLE
[Feature] PChome 商品資料解析

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#45]
身為一個使用者
我希望可以收藏 PChome 的商品
如此我才可以更容易地以更低價格取得商品

* 根據 #11 的結果，實作以下功能
  - 訊息中的 URL parsing 判斷是否為 PChome 商品頁面，進一步取得商品資訊
  - 輸入一個 PChome 的商品 ID 可以取得對應的商品資訊
  
## 商品資訊
1. ID
2. 名稱
3. 價格
4. 商品狀態（可購買、下架、缺貨）

**Comment by ken71301** [comment]
最近有空會開始試這塊，先貼個可能可以參考的連結
https://blog.jiatool.com/posts/pchome_spider01/
