### ISSUE TITLE
[Study] 補齊測試案例

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#6]
身為 開發者
我希望 專案有足夠的測試覆蓋率
如此 才有信心相信程式的品質

# 背景
現在的程式沒有任何測試覆蓋，每次的改動都像是在裸奔，無法確保品質。

# Definition of Done 
1.  要使用何種框架和工具來做測試
2. 有哪些地方需要做測試
4. example code

**Comment by ken71301** [comment]
1. pytest，比python自帶的unittest方便，也可以跟flask的test client連接。
2. 要看架構，如果能給出優先度或是api/function的預定輸入/輸出會比較好。
3. 待補
看有沒有人想一起寫

**Comment by IamSaker** [comment]
pytest 有 patch 好好用 😄
可以先補 endpoint 的測試，再補 unit testing

**Comment by chen-tf** [comment]
https://pypi.org/project/pytest-postgresql/
看看 repository 那邊的是不是也可以補起來
