### ISSUE TITLE
[Study] 採用 ORM framework

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#7]
身為 開發者
我希望 資料持久化的操作可以更簡單
如此 才可以專心在邏輯的操作上

# 背景
目前的 pt_repository 使用的是 psycopg2 和他的 conneciton pool 非常的痛苦，常常會有需要自行檢查是否斷線的問題，想要直接換上一套 ORM framework 在往後的資料操作上才可以更輕鬆。

# Definition of Done 
1.  要使用什麼 python ORM framework
2. 如何把目前的 code migrate 過去
3. example code

**Comment by IamSaker** [comment]
~~@chen-tf 可以換成 [psycopg3](https://www.psycopg.org/psycopg3/docs/) 啦~~
ORM 可以考慮 SQLAlchemy，[conneciton](https://docs.sqlalchemy.org/en/14/core/engines.html#sqlalchemy.create_engine) 看會不會不那麼痛苦

**Comment by chen-tf** [comment]
@IamSaker 或者是我的使用姿勢不太對，但真的挺痛苦的

**Comment by s9891326** [comment]
我來玩玩看好了XD 還沒認真玩過SQLAlchemy

**Comment by s9891326** [comment]
### sqls/create_tables.sql裡面的good_info表
![image](https://user-images.githubusercontent.com/44540755/208842802-05b57383-76fa-4e90-975f-24e7b5e3e908.png)

### 改寫成ORM的models.py
![image](https://user-images.githubusercontent.com/44540755/208842966-c3a5c677-9374-494a-9b1e-ad169dd50333.png)

### 簡單的CRUD
```py
from sqlalchemy.orm import Session

from repository.models import GoodInfo, db
from repository.app import app


def create_good_info(db: Session, data):
    good_info = GoodInfo(**data)
    db.add(good_info)
    db.commit()


def update_good_info(db: Session, good_id, update_data):
    r = db.query(GoodInfo).filter_by(id=good_id).update(update_data)
    db.commit()
    return r


def query_good_info(db: Session, skip: int = 0, limit: int = 100):
    r = db.query(GoodInfo).offset(skip).limit(limit).all()
    db.commit()
    return r


def delete_good_info(db: Session, good_id):
    r = db.query(GoodInfo).filter_by(id=good_id).delete()
    db.commit()
    return r


if __name__ == '__main__':
    with app.app_context():
        good_id = "123"
        good_info_data = {
            "id": good_id,
            "name": "test",
            "price": 456,
        }

        create_good_info(db.session, good_info_data)
        print(query_good_info(db.session))

        print(update_good_info(db.session, good_id, {"name": "test2"}))
        print(query_good_info(db.session))

        print(delete_good_info(db.session, good_id))
        print(query_good_info(db.session))

```
