### ISSUE TITLE
[Study] 調整 readme

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#8]
身為 對這個專案有興趣的開發者
我希望 專案有清楚的 readme 
如此 才可以快速地了解這個專案的背景

# 背景
目前的 readme 比較像是一個故事書...，需要思考一下該做一些什麼調整，讓未來想要 fork project 的人能快速地進入狀態。

# Definition of Done 
1.  如何執行這個專案
2.  想要擴充功能要從何進行
3.  實際上支援幾種指令

**Comment by hokou** [comment]
我的問題是後續會重新調整架構
先以目前架構來調整版面嗎？

目前是想 readme 裡面大概有
1. 更新項目
2. 功能介紹(user)
3. 如何執行(developer)
4. 相關功能的連結 md

然後有一個資料夾專門擺放相關文件.md

**Comment by chen-tf** [comment]
如果是資料夾專門放一些 .md 的話，也可以挪到 GitHub Wiki 上面集中管理
