### ISSUE TITLE
[Study] 重構程式碼

### ISSUE THREAD

**Issue by chen-tf** [chen-tf/price-tracker-bot#9]
身為 開發者
我希望 程式碼可以更簡潔清楚並有清楚的 module scope
如此 我才能有更好的開發效率

# 背景
現況是不同 use case (瀏覽收藏、新增商品、排程檢查價格)的程式碼都摻和在一起，但每個模組間應該要符合 SRP 

# Definition of Done 
1.  需要進行調整的 python file 
2.  調整方式

**Comment by hokou** [comment]
重構也許可以從整合成一個機器開始
或是拿要測試的項目作結合

如果是 flask 有想到一個功能是 `blueprint`
[【Flask 教學】實作 Flask Blueprints 和淺談 Circular Imports](https://www.maxlist.xyz/2020/07/30/flask-blueprint/)
[Python Web Flask — Blueprints 解決大架構的網站](https://medium.com/seaniap/1f9878312526)

**Comment by ken71301** [comment]
blueprint不錯，這部分我也可以幫忙
